name: coleapp
description: "Colecheck - Gestión educativa móvil"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.1.1
  injectable: ^2.7.0
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
